version: "3.3"

services:
  p-api:
    build:
      context: ../../
      dockerfile: ./ops/dev/api.dockerfile
    depends_on:
      - p-lib
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app/
    environment:
      - LINENOTIFY_ENDPOINT=${LINENOTIFY_ENDPOINT}
      - LINENOTIFY_TOKEN=${LINENOTIFY_TOKEN}
      - TYPE=${TYPE}

  p-lib:
    build:
      context: ../../
      dockerfile: ./ops/dev/lib.dockerfile
    volumes:
      - ../../:/app/

  p-workspace:
    build:
      context: ../../
      dockerfile: ./ops/dev/workspace.dockerfile
    working_dir: /app
    ports:
      - "4202:3000"
    volumes:
      - ../../:/app/
    stdin_open: true
    tty: true
