bases:
  - ../../base/
namespace: monitor
namePrefix: prod-

patchesStrategicMerge:
  - ./alertmanager-webhook/horizonalPodAutoScaler-patch.yml
  - ./alertmanager-webhook/deployment-patch.yml

configMapGenerator:
  - name: env-configmap
    behavior: merge
    envs:
      - ./.env
