apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: api-pod
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: app3000
      protocol: TCP
      port: 3000
      targetPort: app3000
