apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-webhook-deployment
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: app
          env:
            - name: TYPE
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: TYPE
            - name: LINENOTIFY_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: LINENOTIFY_ENDPOINT
            - name: LINENOTIFY_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: LINENOTIFY_TOKEN
