commonLabels:
  lab: alertmanager-webhook-lab

commonAnnotations:
  ann: alertmanager-webhook-ann

resources:
  - ./alertmanager-webhook/deployment.yml
  - ./alertmanager-webhook/service.yml
  - ./alertmanager-webhook/horizonalPodAutoScaler.yml

configMapGenerator:
  - name: env-configmap
    envs:
      - ./.env

configurations:
  - ./varReference.yml

vars:
  - name: ALERTMANAGER_WEBHOOK_IMAGE
    objref:
      kind: ConfigMap
      apiVersion: v1
      name: env-configmap
    fieldref:
      fieldpath: data.ALERTMANAGER_WEBHOOK_IMAGE
